### ISSUE TITLE
javascript plain variable regex fails

### ISSUE THREAD

**Issue by klaernie** [winstonwolff/ctags-javascript-coffeescript#1]
the second capture group in [ctags.conf:6](https://github.com/winstonwolff/ctags-javascript-coffeescript/blob/3731d5520b75ad484f4b588838b7f029416e4c24/ctags.conf#L6) seems not to be supported in every ctags version.

error message:

```
ctags: Warning: regcomp ^var[   ]+([a-zA-Z0-9._$]+) = (^{^\[)+: Invalid preceding regular expression
```

I replaced `(^{^\[)+` by `([^{\[])+`, which than correctly matched and didn't throw an error.

```
Exuberant Ctags 5.7, Copyright (C) 1996-2007 Darren Hiebert
  Compiled: Feb 26 2014, 23:57:58
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```

**Comment by winstonwolff** [comment]
Thanks for the fix. I didn't know about that failure. 

I've written a test for variables which I think that line was trying to parse, and I've tweaked the regex to find it.

sha: 14e189b0b068b7d527a55cbaadbac22cd87715a7
